{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.fullname }}
  labels:
    app.kubernetes.io/name: {{ .Values.fullname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.fullname }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    {{- if .Values.networkPolicy.ingress.from }}
    - from:
      {{- toYaml .Values.networkPolicy.ingress.from | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - {} # Allow all egress by default as per previous config, or customize via values
  {{- end }}
{{- end }}
